const arrayLibros = [
    { id: 1, imagen: `https://www.fernandovicente.es/wp-content/uploads/2014/11/Cartel-Estudio-en-escarlata-Fernando-Vicente.jpg`, titulo: `Estudio en escarlata`, autor: `Arthur Conan Doyle`, editorial: `Editorial Bululú`, fechaPublicacion: 1887, resumen: `Watson y Holmes se mudan al 221B de Baker Street, donde Watson se enfrenta a Holmes y a su habilidad para la deducción.
    Holmes es llamado para resolver un asesinato: una casa desierta, un cadáver sin heridas, una misteriosa frase escrita con sangre en la pared.`, precio: 2.949, categoria: `policiacas`
    },

    { id: 2, imagen: `https://www.planetadelibros.com.ar/usuaris/libros/fotos/260/m_libros/portada___201709181757.jpg`, titulo: `Asesinato en el Orient Express`, autor: `Agatha Christie`, editorial: `Collins Crime Club`, fechaPublicacion: 1934, resumen: `Una niña de tres años llamada Daisy Armstrong fue secuestrada por un hombre llamado Cassetti, asesinó a la niña. La muerte de la niña devastó a la familia, provocó varias muertes y suicidios.`, precio: 3.890, categoria: `policiacas` },

    { id: 3, imagen: `https://quelibroleo.com/images/libros/libro_1322105073.jpg`, titulo: `La princesa de hielo`, autor: `Camilla Läckberg`, editorial: `Maeva`, fechaPublicacion: 2003, resumen: `Erica descubre que su amiga, Alex, acaba de suicidarse. Inicia una investigación y descubre que Alex estaba embarazada. La autopsia revela que su amiga no se suicidó sino que fue asesinada. La policía detiene al principal sospechoso, Anders, un artista fracasado.`, precio: 4.500, categoria: `policiacas` },

    { id: 4, imagen: `https://www.storytel.com/images/640x640/0002268294.jpg`, titulo: `Las hijas del frío`, autor: `Camilla Läckberg`, editorial: `OCEANO`, fechaPublicacion: 2005, resumen: `Erica sufre una depresión posparto, encuentra apoyo en Charlotte, madre de Sara. Encuentran el cadáver de Sara, ahogada en el mar. La autopsia revela que fue ahogada en una bañera antes de ser arrojada al mar. Otro niño es atacado; éste vive, pero cunde el pánico en Fjällbacka.`, precio: 4.500, categoria: `policiacas` },

    { id: 5, imagen: `https://contentv2.tap-commerce.com/cover/large/9788494733154_1.jpg?id_com=1113`, titulo: `El faro del fin del mundo`, autor: `Julio Verne`, editorial: `EDITORIAL VERBUM`, fechaPublicacion: 1905, resumen: `Tres guardianes son designados para cuidar un nuevo faro situado en Staten Island, una isla localizada a 200 kilómetros al noreste del Cabo Horn en el Océano Atlántico. Desafortunadamente, la isla cuenta entre sus residentes con un grupo de piratas liderados por Kongre.`, precio: 6.789, categoria: `aventura` },

    { id: 6, imagen: `https://global-uploads.webflow.com/6034d7d1f3e0f52c50b2adee/6254531383a0b15e9a7f0db8_60463d3f9d802109b8311c43_9788418395192_isla20del20tesoro_ClC3A1sicos20Ilustrados_COVER.jpeg`, titulo: `La isla del tesoro`, autor: `Robert Louis Stevenson`, editorial: `PlanetadeLibros`, fechaPublicacion: 1883, resumen: `Un grupo de aventureros van a la búsqueda de un tesoro enterrado en una isla por un viejo pirata. Narrada en primera persona por el joven marinero Jim Hawkins, contiene una expedición a tierras lejanas y desconocidas, peligros, piratas y un tesoro escondido.`, precio: 2.340, categoria: `aventura` },

    { id: 7, imagen: `https://www.penguinlibros.com/ar/1592872/robinson-crusoe-edicion-ilustrada.jpg`, titulo: `Robinson Crusoe`, autor: `Daniel Defoe`, editorial: `Editorial Alma`, fechaPublicacion: 1719, resumen: `Un marinero es el único superviviente. Abandonado en una isla desierta, hace lo posible por mantenerse con vida hasta lograr escapar de su prisión de agua y arena. Sólo su ingenio podrá salvarlo de los peligros y de las amenazas de las islas vecinas.`, precio: 8.000, categoria: `aventura` },

    { id: 8, imagen: `https://images.cdn3.buscalibre.com/fit-in/360x360/4e/10/4e104e6aa9cebad79a8919a83485210a.jpg`, titulo: `El lobo de mar`, autor: `Jack London`, editorial: `AKAL EDICIONES`, fechaPublicacion: 1904, resumen: ` Humphrey van Weyden es un joven intelectual e idealista que, tras naufragar en un ferry en aguas del pacífico, es rescatado por un barco capitaneado por Wolf Larsen, es cruel, despiadado y sin escrúpulos. Sometido a su tiránica autoridad, el joven descubrirá la dureza y la impiedad de un mundo primitivo.`, precio: 3.699, categoria: `aventura` },

    { id: 9, imagen: `https://www.penguinlibros.com/ar/1590029/el-problema-de-los-tres-cuerpos-trilogia-de-los-tres-cuerpos-1.jpg`, titulo: `El problema de los tres cuerpos`, autor: `Liu Cixin`, editorial: `Gnome Press`, fechaPublicacion: 1950, resumen: `Un videojuego de historia. Los alienígenas empiezan a ganar a los jugadores, se forman dos bandos, unos dispuestos a dar la bienvenida y ayudarlos a cambiar el mundo, y otros para luchar contra la invasión.`, precio: 7.699, categoria: `ciencia ficcion` },

    { id: 10, imagen: `https://images.cdn1.buscalibre.com/fit-in/360x360/79/2f/792f48e890d9c589ffc9c9a1a8259306.jpg`, titulo: `Yo, robot`, autor: `Isaac Asimov`, editorial: `Editorial Nova`, fechaPublicacion: 1973, resumen: `En el futuro cibernético (de 2047 a 2064) los robots y humanos conviven. Se dan conflictos que hacen poner sobre la mesa la ética del asunto. Los final son prometedor, ya que todos los robots se rigen por las tres Leyes de la Robótica. Siempre deben procurar el bien para los humanos y cumplir sus órdenes.`, precio: 8.399, categoria: `ciencia ficcion` },

    { id: 11, imagen: `https://http2.mlstatic.com/D_NQ_NP_816143-MLA54516896141_032023-V.jpg`, titulo: `Cita con Rama`, autor: `Arthur C. Clarke`, editorial: `Ediciones B`, fechaPublicacion: 2008, resumen: `El impacto de un asteroide que destruye Padua y Verona, se crea un sistema para detectar cualquier objeto desde la Tierra. Se detecta Rama, un asteroide que gira a un velocidad increíble y que no volverá a pasar por el sistema solar. Aparecen indicios de que Rama pueda ser artificial, con las implicaciones que ello conlleva`, precio: 10.792, categoria: `ciencia ficcion` },

    { id: 12, imagen: `https://quelibroleo.com/images/libros/libro_1322102944.jpg`, titulo: `Fundación`, autor: `Isaac Asimov`, editorial: `Cenit`, fechaPublicacion: 1951, resumen: `El hombre se ha dispersado por los planetas de la galaxia, unificada alrededor de un Imperio pacífico cuya capital es Trántor. El sistema funcionó durante incontables generaciones, pero se ha convertido en el símbolo de la corrupción imperial. Solamente Hari Seldon fue capaz de prever el derrumbamiento del Imperio.`, precio: 7.199, categoria: `ciencia ficcion`},

    { id: 13, imagen: `https://quelibroleo.com/images/libros/libro-1549448677.jpg`, titulo: `Amante oscuro`, autor: `Jessica Bird`, editorial: `SUMA`, fechaPublicacion: 2019, resumen: `se desarrolla una guerra entre los vampiros y sus verdugos… En ella destaca una hermandad de seis vampiros. Wrath arrastra a la bella joven al mundo de los no-muertos… Beth Randall es incapaz de resistirse, es increíblemente atractivo, que la visita cada noche.`, precio: 3.237, categoria: `paranormales` },

    { id: 14, imagen: `https://www.elojolector.com/wp-content/uploads/2013/09/que-nunca-amanezca-ebook-9788408117186.jpg`, titulo: `Que nunca amanezca`, autor:`Abigail Gibbs`, editorial: `PLANETA`, fechaPublicacion: 2012, resumen: `Antes de que pudiera decir una sola palabra más, Kaspar empujó contra la pared y comenzó a recorrerme el cuello con los labios. Se le agitó la respiración y sentí su fuerza, su poder, su hambre. Me dejó helada y provocó que un escalofrío me recorriera los hombros y los brazos.`, precio: 7.800, categoria: `paranormales` },

    { id: 15, imagen: `https://www.planetadelibros.com.ar/usuaris/libros/fotos/371/m_libros/portada_el-encanto-del-cuervo_maria-martinez_202212051623.jpg`, titulo: `El encanto del cuervo`, autor:`María Martínez`, editorial: `Booket`, fechaPublicacion: 2013, resumen: `La vida de Abby cambia por completo, despues de la muerte de su madre, ahora tiene amigos, familia y un lugar. La atormentan terribles pesadillas y esa sensación de sentirse observada. El peligro está cerca y acecha como la sombra de un cuervo en la oscuridad.`, precio: 6.300, categoria: `paranormales`},

    { id: 16, imagen: `https://www.penguinlibros.com/ar/1593815/oscuros-oscuros-1.jpg`, titulo: `Oscuros`, autor:`Lauren Kate`, editorial: `SUDAMERICANA`, fechaPublicacion: 2009, resumen: `Daniel no quiere nada con Luce. Pero Luce no lo puede dejar ir. Está empeñada en averiguar qué secretos guarda Daniel, aunque le cueste la vida. En el proceso, Luce descubrirá que esta historia de amor aparentemente nueva tiene un origen que se remonta miles de años atrás un origen más trágico y formidable.`, precio: 5.400, categoria: `paranormales` },

    { id: 17, imagen: `https://www.penguinlibros.com/ar/1596498/bajo-la-misma-estrella.jpg`, titulo: `Bajo la misma estrella`, autor:`John Green`, editorial: `Dutton Books`, fechaPublicacion: 2012, resumen: `Hazel y Gus son dos adolescentes que comparten un mordaz ingenio, un desdén por lo convencional y un amor que los arrastra a un viaje inolvidable. Su relación resulta milagrosa cuando conocieron y enamoraron en un grupo de apoyo a enfermos de cáncer`, precio: 5.500, categoria: `romanticas` },

    { id: 18, imagen: `https://www.planetadelibros.com.ar/usuaris/libros/fotos/282/m_libros/portada_zafiros-en-la-piel_viviana-rivero_201808241754.jpg`, titulo: `Zafiros en la piel`, autor:`Viviana Rivero`, editorial: `EMECE`, fechaPublicacion: 2018, resumen: `El amor, ese sentimiento poderoso, recorre las páginas de los doce relatos que integran Zafiros en la piel. Desinteresado, erótico, altruista, fraternal, obsesivo, apasionado, sacrificado, abrasador: sus variantes son múltiples como los personajes de estas historias.`, precio: 2.000, categoria: `romanticas` },

    { id: 19, imagen: `https://cloudfront-us-east-1.images.arcpublishing.com/infobae/ODUTXENZ3VBNXLCGNEWITFO4TM.jpg`, titulo: `Lo que el viento se llevó`, autor:`Margaret Mitchell`, editorial: `Macmillan Publishers`, fechaPublicacion: 1936, resumen: `Rhett Butler, está enamorado de Scarlett, pero ésta prefiere vengarse de Melanie casándose con su hermano Charles. Cuando la guerra cese, Scarlett habrá enviudado, y Batler intentará de nuevo seducirla.`, precio: 6.300, categoria: `romanticas` },

    { id: 20, imagen: `https://contentv2.tap-commerce.com/cover/large/9789504976646_1.jpg?id_com=1113`, titulo: `El cuarto arcano`, autor:`Florencia Bonelli`, editorial: `PLANETA`, fechaPublicacion: 2007, resumen: `Roger Blackraven es un hombre de negocios cuyo interés radica en Buenos Aires, donde es dueño de tierras. Melody Maguire es una joven criolla de padre irlandés, el cual huyó de su tierra natal. Cuando las vidas de Roger y de Melody se crucen, cambiarán para siempre`, precio: 6.400, categoria: `romanticas` },

    { id: 21, imagen: `https://www.rocalibros.com/archivos/imagenes/mayores/2593.jpg`, titulo: `Sé lo que estás pensando`, autor:`John Verdon`, editorial: `Roca Editoria`, fechaPublicacion: 2010, resumen: `Un hombre recibe una carta que le urge a pensar en un número, cualquiera. Cuando abre el pequeño sobre, siguiendo las instrucciones que figuran en la propia carta, se da cuenta de que el número allí escrito es el que había pensado.`, precio:3.153, categoria: `policiacas` },

    { id: 22, imagen: `https://2.bp.blogspot.com/-ERSG7Pi4L4M/V_cDT5eE2pI/AAAAAAAABNM/heqYtTzLRQ8679mRRE1Fvys49xLJHJ5uACLcB/s1600/3215.jpg`, titulo: `Los crímenes de la calle Morgue`, autor:`Edgar Allan Poe`, editorial: `FCE`, fechaPublicacion: 1841, resumen: `Un crimen horrendo que aterroriza a todos. La solución del crimen si será compleja: el detective aficionado Lupin, con su tremenda capacidad analitica, resuelve el enrevesado misterio.`, precio: 4.600, categoria: `policiacas` },

    { id: 23, imagen: `https://www.planetadelibros.com.ar/usuaris/libros/fotos/97/m_libros/96250_pasado-perfecto_9788483831472.jpg`, titulo: `Pasado perfecto`, autor:`Leonardo Padura`, editorial: `Planeta Publishing`, fechaPublicacion: 1991, resumen: `Al teniente Mario Conde, un policía escéptico y desengañado, lo llaman para encargarle un misterioso y urgente caso: Rafael Morín. Irá descubriendo que el aparente pasado perfecto sobre el que Rafael Morín ha ido labrando su brillante carrera ocultaba ya sus sombras.`, precio: 2.599, categoria: `policiacas` },

    { id: 24, imagen: `https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1501251400i/6135735.jpg`, titulo: `Los vecinos mueren en las novelas`, autor:`Aguirre Sergio`, editorial: `NORMA`, fechaPublicacion: 2000, resumen: `Robert, es un hombre infeliz en su matrimonio por lo que busca un amante y se enamora pero no puede dejar a su esposa. Entonces la amante, cansada de tanto esperar, mata a la esposa pero haciendo que todo parezca un accidente.`, precio: 3.100, categoria: `policiacas` },

    { id: 25, imagen: `https://www.ellibrototal.com/testLtotal/CARATULAS/libros/2011/8/6116.jpg`, titulo: `De la Tierra a la Luna`, autor:`Julio Verne`, editorial: `Hetzel`, fechaPublicacion: 1865, resumen: `Se trata de enviar a la Luna un proyectil que, auxiliado por el monstruoso cañón Columbiad, hará la función de una auténtica nave espacial para hacer realidad en el siglo XIX un viejo sueño: atravesar el espacio y descubrir un mundo lunar hasta entonces en penumbras.`, precio: 3.200, categoria: `aventura` },

    { id: 26, imagen: `https://2.bp.blogspot.com/-m4_GfcWYRYw/XMhnHNFAC6I/AAAAAAAALwk/UK3oHpJgl-kaPq4343mE7LGFE6HhZCmKQCLcBGAs/s1600/BL24343.jpg`, titulo: `La leyenda del bosque`, autor:`Jara Santamaría`, editorial: `B DE BLOCK`, fechaPublicacion: 2019, resumen: `3 primos que no se llevan bien, pero las circunstancias han querido que coincidan durante las vacaciones en la casas de su abuela. Cuando uno de los 3 desaparece, los otros se lanzan su búsqueda y descubren que la unión de todos es mucho más fuerte de lo que creían.`, precio: 2.000, categoria: `aventura` },

    { id: 27, imagen: `https://www.planetadelibros.com.ar/usuaris/libros/fotos/267/m_libros/266762_portada_la-puerta-de-los-tres-cerrojos_sonia-fernandez-vidal_201802191022.jpg`, titulo: `La puerta de los tres cerrojos`, autor:`Sonia Fernández-Vidal`, editorial: `PlanetadeLibros`, fechaPublicacion: 2011, resumen: `Después de recibir un mensaje, Niko recorre un nuevo camino para ir al instituto y descubre una casa. La resolución de un enigma le permite entrar en lo que resultará ser un extraño lugar donde nacen universos.`, precio: 6.614, categoria: `aventura` },

    { id: 28, imagen: `https://http2.mlstatic.com/D_NQ_NP_642670-MLA49523153613_032022-O.jpghttps://www.planetadelibros.com.ar/usuaris/libros/fotos/267/m_libros/266762_portada_la-puerta-de-los-tres-cerrojos_sonia-fernandez-vidal_201802191022.jpg`, titulo: `Muerte en el Nilo`, autor:`Agatha Christie`, editorial: `Booket`, fechaPublicacion: 1937, resumen: `Unas apacibles vacaciones en Egipto de una pareja de recién casados se truncan con un asesinato. La joven Linnet aparece muerta durante el crucero por el Nilo. Tiene un disparo en la cabeza. El detective Hércules Poirot será el encargado de resolver el misterio.`, precio: 4.600, categoria: `aventura` },

    { id: 29, imagen: `https://3.bp.blogspot.com/--Bqa7zb5cYw/VghQP-xH7RI/AAAAAAAAdnU/tKh0Yh8dQ84/s1600/El%2BMarciano%2Bde%2BAndy%2BWeir-1.jpg`, titulo: `El marciano`, autor:`Andy Weir`, editorial: `B de bolsillo`, fechaPublicacion: 2011, resumen: `La tripulación de la nave en que viajaba se ve obligada a evacuar el planeta a causa de una tormenta de polvo, dejando atrás a Mark tras darlo por muerto. Pero él está vivo, y atrapado a millones de kilómetros de cualquier ser humano, sin posibilidad de enviar señales a la Tierra.`, precio: 3.432, categoria: `ciencia ficcion` },

    { id: 30, imagen: `https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1565155232l/52543442.jpg`, titulo: `El libro negro`, autor:`Orhan Pamuk`, editorial: `Ediciones Martínez Roca`, fechaPublicacion: 1951, resumen: `Así cuenta su caso Galip, un joven abogado que vive en Estambul y quiere reencontrarse con Rüya, su esposa. Sospecha que ha huido con otro hombre, con un hombre que bien podría ser alguien muy cercano, casi tan cercano como su propio hermanastro. Galip recorre día y noche las calles de un Estambul real y descubre una historia secreta.`, precio: 5.300, categoria: `ciencia ficcion` },

    { id: 31, imagen: `https://images.cdn2.buscalibre.com/fit-in/360x360/3e/4c/3e4c6191a61a6c81b17b266a88824863.jpg`, titulo: `Panteón`, autor:`Carlos Sisí`, editorial: `Minotauro `, fechaPublicacion: 2013, resumen: `La Tierra, explotó hace diez mil años. El hombre ya había iniciado su periplo por el espacio. En esta nueva Era, la guerra y la paz son elementos de una misma balanza que se equilibran desde La Colonia. Desde allí, la controladora Maralda Tardes detecta actividad bélica en un planeta alejado, y decide iniciar un protocolo estándar de inspección.`, precio: 3.650, categoria: `ciencia ficcion` },

    { id: 32, imagen: `https://www.mrwonderbook.com/wp-content/uploads/2022/04/Proyecto-Hail-Mary.jpg`, titulo: `Proyecto Hail Mary`, autor:`Andy Wei`, editorial: `NOVA `, fechaPublicacion: 2021, resumen: `La deslumbrante historia de un astronauta solitario que tiene la misión de salvar a la Tierra de la amenaza de una bacteria alienígena. Ryland Grace es el único superviviente en una misión desesperada. Si falla, la humanidad y la Tierra perecerán.`, precio: 7.699, categoria: `ciencia ficcion` },

    { id: 33, imagen: `https://quelibroleo.com/images/libros/libro_1301243107.png`, titulo: `El ángel caído`, autor:`Nalini Singh`, editorial: `Valdemar`, fechaPublicacion: 2009, resumen: `Luzbel y un ejercito de ángeles se rebelaron contra de El Padre e iniciaron la más terrible de las guerras. El ejercito del Príncipe de Fuego estuvo a punto de alcanzar la victoria, pero en un último enfrentamiento heroico, fue vencido y confinado a una incandescente prisión de odio. Desde ese lugar planea su venganza.`, precio: 6.939, categoria: `paranormales` },

    { id: 34, imagen: `https://m.media-amazon.com/images/I/5131BMrvyrL.jpg`, titulo: `Insomnio`, autor:`Maite Aleu`, editorial: `Independently published`, fechaPublicacion: 2020, resumen: `Roxanna Stone tiene un trabajo que le gusta, una peculiaridad que la hace distinta y un pasado que prefiere olvidar. Una noche, tras un extraño episodio de amnesia, sueña con un enigmático desconocido. A partir de ahí se sumergirá en un mundo de pasión sin límites, donde se mezclan los sueños y la realidad.`, precio: 3.800, categoria: `paranormales` },

    { id: 35, imagen: `https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTQzex3FKxJKc9wSz4WsAKEzqd353BssTEEEAYkTe2NzHJ1worI0lUar4EYH5FrsPTn7KA&usqp=CAU`, titulo: `El deseo oscuro`, autor:`Christine Feehan`, editorial: `EDICIONES URANO`, fechaPublicacion: 1999, resumen: `Shea tiene que dejar su trabajo en EEUU y huir a través de toda Europa, perseguida por unos fanáticos que asocian los síntomas de su enfermedad con el vampirismo. Se siente atraída hasta los Cárpatos, en Rumanía, donde encuentra a un hombre en una vieja cripta.`, precio: 11.772, categoria: `paranormales` },

    { id: 36, imagen: `https://www.eltemplodelasmilpuertas.com/biblioteca/portadas/eclipse.jpg`, titulo: `Eclipse`, autor:`Stephenie Meyer`, editorial: `RESERVOIR BOOKS`, fechaPublicacion: 2007, resumen: `Bella Swan vuelve a encontrarse rodeada de peligros, mientras Seattle se ve asolada por una oleada de misteriosos asesinatos y una maliciosa vampira prosigue su búsqueda de venganza. En medio de todo eso, Bella se ve obligada a elegir entre su amor por Edward Cullen y su amistad con Jacob Black`, precio: 5.100, categoria: `paranormales` },

    { id: 37, imagen: `https://images.cdn2.buscalibre.com/fit-in/360x360/c9/75/c975b675606573f2d27cbe8185644262.jpg`, titulo: `Forastera`, autor:`Diana Gabaldon`, editorial: `SALAMANDRA `, fechaPublicacion: 1991, resumen: `Una pareja se encuentran con que el mundo moderno ha desaparecido, ahora los rodea la Escocia de 1734, con sus clanes beligerantes, hombres y mujeres rudos, violentos, pero con una capacidad de amar que Claire nunca habia visto. Claire tendrá que elegir entre la seguridad del futuro y la incertidumbre del pasado.`, precio: 7.699, categoria: `romanticas` },

    { id: 38, imagen: `https://images.cdn2.buscalibre.com/fit-in/360x360/f0/0f/f00f33aec4395aad070045e9cbd5d8f6.jpg`, titulo: `El Lenguaje del Alma`, autor:`Josep Soler`, editorial: `Gaia Ediciones `, fechaPublicacion: 2015, resumen: `Josep Soler explica cómo el cuerpo tiene un lenguaje propio que nos da información constantemente a través de los diferentes cuerpos (físico, energético, emocional, mental y espiritual) que tenemos. Explican las herramientas para alinearse con el propósito de vida.`, precio: 8.000, categoria: `romanticas` },

    { id: 39, imagen: `https://images.cdn3.buscalibre.com/fit-in/360x360/e5/17/e517246b186a26ad496c608e918d608f.jpg`, titulo: `Llámame por tu nombre`, autor:`André Aciman`, editorial: `Farrar`, fechaPublicacion: 2007, resumen: `Un joven estudiante viaja a Italia para profundizar en sus estudios de Filosofía durante un verano. El hermoso pueblo costero en el que se instala servirá para narrar una historia de amor que marcará su vida y la del hijo adolescente de la familia que le acoge.`, precio: 6.799, categoria: `romanticas` },

    { id: 40, imagen: `https://images.cdn2.buscalibre.com/fit-in/360x360/c4/82/c4821d521f27c5f92eb2443674790ef5.jpg`, titulo: `En nombre del amor`, autor:`Nicholas Sparks`, editorial: `Roca editorial`, fechaPublicacion: 2007, resumen: `Travis Parker Un buen trabajo como veterinario, amigos fieles y una casa delante de un lago. Pero hay algo que se resiste a probar: enamorarse. Sin embargo, semejante propósito desaparece por completo en el momento en que aparece en su vida Gabby Holland.`, precio: 12.710, categoria: `romanticas` },
];

const carrito = ["Hola"];
